# maketree.py
# Purpose: Fast, accurate project tree generator that extracts the 4-line header from every real .py source file.
# Major APIs: generate_project_tree()
# Notes: Excludes junk dirs, skips large files, no double-counting. Run from project root.

import os
from pathlib import Path
from typing import List

ROOT = Path(__file__).parent.resolve()
OUTPUT_FILE = ROOT / "project_tree.txt"

# Strict exclude — these folders contain zero real source code
EXCLUDE_DIRS = {
    ".git", "__pycache__", ".venv", "venv", "env", "build", "dist",
    ".pytest_cache", "results", "data", "logs", "core/live"  # live not created yet
}

# Skip known non-source Python files
EXCLUDE_FILES = {"maketree.py"}  # don't include self in count if you want

def extract_header(content: str) -> List[str]:
    lines = []
    for line in content.splitlines()[:12]:
        line = line.rstrip()
        if line.startswith("#"):
            clean = line.lstrip("# ").strip()
            if clean:
                lines.append(clean)
        elif lines:
            break
        if len(lines) >= 4:
            break
    return lines[:4]

def scan_directory(path: Path, entries: List[str], processed_files: set):
    try:
        items = sorted(path.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
    except PermissionError:
        return

    for item in items:
        if item.name in EXCLUDE_DIRS or item.name.startswith('.'):
            continue

        if item.is_dir():
            rel_dir = item.relative_to(ROOT)
            entries.append(f"\n{rel_dir}/")
            scan_directory(item, entries, processed_files)
        
        elif item.suffix == ".py" and item.name not in EXCLUDE_FILES:
            if item.stat().st_size > 2_000_000:  # skip huge generated files
                continue
                
            rel_file = item.relative_to(ROOT)
            file_key = str(rel_file)
            if file_key in processed_files:
                continue
            processed_files.add(file_key)
            
            try:
                header = extract_header(item.read_text(encoding="utf-8", errors="ignore"))
                entries.append(f"{rel_file}")
                if header:
                    for h in header:
                        entries.append(f"  - {h}")
                else:
                    entries.append("  (no header found)")
                entries.append("")
            except Exception as e:
                entries.append(f"{rel_file}\n  - ERROR: {e}\n")

def generate_project_tree() -> None:
    print("Generating accurate project_tree.txt...")
    entries = [
        "# project_tree.txt",
        "# AUTO-GENERATED by maketree.py — DO NOT EDIT MANUALLY",
        "# Contains only real source .py files + their 4-line headers",
        "="*80,
        f"ROOT: {ROOT}",
        "="*80,
        ""
    ]
    
    processed = set()
    scan_directory(ROOT, entries, processed)
    
    OUTPUT_FILE.write_text("\n".join(entries), encoding="utf-8")
    real_count = len(processed)
    print(f"Done! project_tree.txt written with exactly {real_count} real source .py files.")

if __name__ == "__main__":
    generate_project_tree()

# maketree.py v1.3 (95 lines)